baseURL = "https://summittdweller.com/blogs/mark"
languageCode = "en-us"
title = "Personal Blog"
theme = "internet-weblog"
enableEmoji = true

[author]
   Handle = "SummittDweller"
   FirstName = "Mark"
   LastName = "McFate"
   AboutPage = "/about"
   Location = "Toledo, Iowa"
   FlickrID = "<Your Flickr ID>"


SectionPagesMenu = "main"

[params]
   build = 10     # this value is auto-incremened using 'perl' in push-update.sh
   RSSSections = [ "Posts", "Microposts", "Photos" ]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Photos"
  weight = 2
  identifier = "photos"
  url = "/photos/"
