baseURL = "http://example.org/"
languageCode = "en-us"
title = "Personal Blog"
theme = "internet-weblog"

[author]
   Handle = "SummittDweller"
   FirstName = "Mark"
   LastName = "McFate"
   AboutPage = "/about"
   Location = "Grinnell, Iowa"
   FlickrID = "<Your Flickr ID>"


SectionPagesMenu = "main"

[params]
   RSSSections = [ "Posts", "Microposts", "Photos" ]

[[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Photos"
  weight = 2
  identifier = "photos"
  url = "/photos/"
